/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectoempleados.ManejoEmpleado;
import proyectoempleados.Empleado;
import proyectoempleados.ManejoArchivo;

/**
 *
 * @author SergioSystem
 */

public class frmproyectoempleado extends javax.swing.JFrame {
    
    //Variables Globales
    DefaultTableModel modelo;
    ManejoEmpleado ManagerEmpleado;
    ManejoArchivo ManagerArchivo;
    
    /**
     * Creates new form frmproyectoempleado
     */
    public frmproyectoempleado() {
        initComponents();
        Init();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        txtnombres = new javax.swing.JTextField();
        txtsalario = new javax.swing.JTextField();
        txtnacimiento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btneliminarlote = new javax.swing.JButton();
        btnguardarduro = new javax.swing.JButton();
        btnrecuperarduro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("APELLIDOS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRES");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("SALARIO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("FECHA NACIMIENTO");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        btnagregar.setText("AGREGAR");
        btnagregar.setName(""); // NOI18N
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btneliminar.setText("ELIMINAR");
        btneliminar.setName(""); // NOI18N
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btneliminarlote.setText("ELIMINAR LOTE");
        btneliminarlote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarloteActionPerformed(evt);
            }
        });

        btnguardarduro.setText("GUARDAR PLANILLA EN DISCO DURO");
        btnguardarduro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarduroActionPerformed(evt);
            }
        });

        btnrecuperarduro.setText("RECUPERAR PLANILLA DE DISCO DURO");
        btnrecuperarduro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecuperarduroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel5.setText("PLANILLA DE EMPLEADOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtapellidos)
                            .addComponent(txtnombres)
                            .addComponent(txtsalario)
                            .addComponent(txtnacimiento))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnguardarduro, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnagregar)
                                .addGap(18, 18, 18)
                                .addComponent(btneliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btneliminarlote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnrecuperarduro, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 49, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregar)
                    .addComponent(btneliminar)
                    .addComponent(btneliminarlote))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardarduro)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrecuperarduro))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Este metodo sirve para inicializar las variables cuendo cargue el formulario
    private void Init(){
        modelo=new DefaultTableModel();
        modelo.addColumn("APELLIDOS");
        modelo.addColumn("NOMBRES");
        modelo.addColumn("SALARIO");
        modelo.addColumn("FECHA DE NACIMIENTO");
        this.tabla.setModel(modelo); 
        
        //Instanciona nuestro gestor de empleados
        this.ManagerEmpleado = new ManejoEmpleado();
        //Instanciamos el manager archivo con la ruta del archivo
        this.ManagerArchivo = new ManejoArchivo("C:\\Users\\COMPU.CHEX\\Documents\\"
                + "NetBeansProjects\\proyectoempleados\\proyectoempleados\\src\\Empleado.txt");
    }
    
    
    private void LimpiarTextBox(){
        txtapellidos.setText("");
        txtnombres.setText("");
        txtsalario.setText("");
        txtnacimiento.setText("");
    }
    private void Prueba(){
        /*Empleado E1 = new Empleado("Roy","Reategui",5000,"12/05/2015");
        Empleado E2 = new Empleado("Amalia","Aguila",400,"12/05/2015");
        Empleado E3 = new Empleado("Luz","Delgado",4000,"12/05/2015");
        
        this.ManagerEmpleado.AddEmpleado(E1);
        this.ManagerEmpleado.AddEmpleado(E2);
        this.ManagerEmpleado.AddEmpleado(E3);*/
        
        this.ManagerEmpleado.setListaEmpleado(this.ManagerArchivo.LeerArchivo());
        
        for(Empleado E: this.ManagerEmpleado.getListaEmpleado()){
            modelo.addRow(new Object[]{E.getNombre(),
            E.getApellido(), ""+E.getSalario(),
            E.getNacimiento()});
        }

    }
    
    
    private void Cargar(){
      //Limpiamos la tabla
      this.modelo.setRowCount(0);
              
      for(Empleado E: this.ManagerEmpleado.getListaEmpleado()){
            modelo.addRow(new Object[]{E.getNombre(),
            E.getApellido(), ""+E.getSalario(),
            E.getNacimiento()});
        }  
    }
    
    
    
    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        
      
        
        //Agregamos los tados en la tabla del formulario
        modelo.addRow(new Object[]{txtnombres.getText(),
            txtapellidos.getText(),txtsalario.getText(),
            txtnacimiento.getText()});
        
        
        
        this.LimpiarTextBox();
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnrecuperarduroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecuperarduroActionPerformed
        // TODO add your handling code here:
        this.modelo.setRowCount(0);
        Prueba();
    }//GEN-LAST:event_btnrecuperarduroActionPerformed

    private void btnguardarduroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarduroActionPerformed
        // TODO add your handling code here:
        
        int lenght = this.modelo.getRowCount();
        
        if(lenght > 0){
            this.ManagerArchivo.EcribirArchivo("",true);
            for (int i = 0; i < lenght; i++) {
               Empleado EmpleadoNuevo = new Empleado();
               
               EmpleadoNuevo.setNombre(""+this.modelo.getValueAt(i,0));
               EmpleadoNuevo.setApellido(""+this.modelo.getValueAt(i,1));
               EmpleadoNuevo.setSalario(Double.parseDouble(""+this.modelo.getValueAt(i,2)));
               EmpleadoNuevo.setNacimiento(""+this.modelo.getValueAt(i,3));
               System.out.println(EmpleadoNuevo);
               this.ManagerEmpleado.AddEmpleado(EmpleadoNuevo);
               
               //Agregamos los datos al archivo
                this.ManagerArchivo.EcribirArchivo(EmpleadoNuevo.toString(),false);
            }
        }
        
        
        
        
        
    }//GEN-LAST:event_btnguardarduroActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        int filaseleccionada = tabla.getSelectedRow();
        if(filaseleccionada>=0){
            this.ManagerEmpleado.Delete(filaseleccionada);
            this.Cargar();
        }else{
            JOptionPane.showMessageDialog(null,"LA TABLA ESTA VACIA O NO SELECCIONO UNA LINEA DE LA PLANILLA");
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btneliminarloteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarloteActionPerformed
        // TODO add your handling code here:
        int fila=tabla.getRowCount();
        for(int i=fila-1;i>=0;i--){
           modelo.removeRow(i);
        }     
    }//GEN-LAST:event_btneliminarloteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmproyectoempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmproyectoempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmproyectoempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmproyectoempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmproyectoempleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btneliminarlote;
    private javax.swing.JButton btnguardarduro;
    private javax.swing.JButton btnrecuperarduro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtnacimiento;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtsalario;
    // End of variables declaration//GEN-END:variables
}
